version: 2
updates:
  # Configuration for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Europe/Paris'
    ignore:
      # Ignore updates to packages that start with '@nx'
      # Wildcards match zero or more arbitrary characters
      - dependency-name: '@nx*'
      - dependency-name: 'nx'
      # Ignore all updates for angular
      - dependency-name: '@angular*'
      - dependency-name: 'ng-packagr'
      - dependency-name: '@schematics/angular'
      - dependency-name: 'angular-eslint'
      - dependency-name: 'verdaccio'
