name: Supabase Nx CI

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Use Postgres container for local testing
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Supabase local development
        run: |
          npx supabase start
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Run database migrations
        run: |
          cd supabase/migrations
          for file in *.sql; do
            echo "Running migration: $file"
            PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f "$file"
          done

      - name: Run database seed
        run: |
          cd supabase/seed
          PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f seed.sql

      - name: Lint
        run: npx nx run-many --target=lint --all

      - name: Build
        run: npx nx run-many --target=build --all

      - name: Test
        run: npx nx run-many --target=test --all
        env:
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
          NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0

      - name: E2E Tests
        run: npx nx run-many --target=e2e --all
        env:
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
          NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0

      - name: Check for SQL syntax errors
        run: |
          cd supabase/migrations
          for file in *.sql; do
            echo "Checking syntax for: $file"
            cat "$file" | PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f - >/dev/null || exit 1
          done
